server:
  name: chainlp
  port: 80
  tomcat:
    threads:
      max: 20
  error:
    include-stacktrace: never

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # [ validate, create, update, none, create-drop ]
  datasource:
    hikari:
      maximumPoolSize: 20
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.aventstack: DEBUG
    org.springframework: INFO
